#!/bin/sh

set -e

lb config noauto \
  --distribution trixie \
  --parent-distribution trixie \
  --architectures amd64 \
  --debian-installer none \
  --archive-areas "main contrib non-free non-free-firmware" \
  --memtest none \
  "${@}"
